### ISSUE TITLE
attachment

### ISSUE THREAD

**Issue by GT9527** [baolongnguyenmac/fl-ml#3]
Your work is excellent. Where can I download the attachment of your paper?

**Comment by baolongnguyenmac** [comment]
Thank you!

You can download the paper from [Springer](https://link.springer.com/chapter/10.1007/978-3-031-21743-2_17).
Or you can get the original version at `./document/paper/Meta-learning and Personalization layer in FL.pdf`

**Comment by GT9527** [comment]
Thanks, I downloaded your paper, but I didn't find the Appendix A.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "baolongnguyenmac/fl-ml"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月2日(星期四) 下午4:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [baolongnguyenmac/fl-ml] attachment (Issue #3)





 
Thank you!
 
You can download the paper from Springer.
 Or you can get the original version at ./document/paper/Meta-learning and Personalization layer in FL.pdf

**Comment by baolongnguyenmac** [comment]
I have just checked both the version in `./document/paper/Meta-learning and Personalization layer in FL.pdf` and the final version that I submitted to the conference. Appendix A should be right there in page 12 :v 

<img width="682" alt="image" src="https://user-images.githubusercontent.com/46776838/216278852-62482862-1b26-4163-ae96-5b69d17a6a45.png">

**Comment by GT9527** [comment]
Thank you! I didn't read it carefully.
